### ISSUE TITLE
Opencorporates link broken

### ISSUE THREAD

**Issue by anderspeders** [NRGI/rp-org-frontend#58] opened 2016-03-28 16:44 UTC
An error in auto-linking to OC

Example: 
http://dev.resourceprojects.org/company/56f6c0dcb5eafb01007ed33b

Links to this URL: 
https://opencorporates.com/companies/https://opencorporates.com/companies/je/EXTUID_24670

**Comment by mattfullerton** [comment] 2016-03-28 16:49
Duplicate of #55

**Comment by byndcivilization** [comment] 2016-03-29 18:40
As a quick fix im changing the template. Let me know when ETL is pulling OC id.

**Comment by mattfullerton** [comment] 2016-03-30 05:41
I've fixed ETL and changed the template back

**Closed by mattfullerton** 2016-03-30 05:41 UTC
Labels: bug, ETL
